#!/usr/bin/env node


import { Command } from 'commander';
import { main } from './src/cli.js';
import fs from 'fs';
import path from 'path';

const CONFIG_PATH = path.resolve(process.cwd(), '.mo3ta-coverage.json');

function readConfig() {
  console.log(`Reading config from: ${CONFIG_PATH}`);
  
  if (fs.existsSync(CONFIG_PATH)) {
    return JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
  }
  return {};
}

function writeConfig(config) {
  fs.writeFileSync(CONFIG_PATH, JSON.stringify(config, null, 2));
  console.log(`Updated config: ${JSON.stringify(config, null, 2)}`);
}

const program = new Command();

program
  .name('mo3ta-coverage')
  .description('Run tests and report uncovered changed lines in a PR. Checks cumulative coverage for all changed lines against a specified limit. Useful for CI and code review workflows.');

program
  .option('--base <branch>', 'Base branch to compare against (e.g., origin/main)')
  .option('--lcov <path>', 'Path to lcov.info file generated by test coverage tools', 'coverage/lcov.info')
  .option('--limit <percent>', 'Minimum required coverage percentage for all changed lines (e.g., 80)', '80')
  .option('--showCovered <bool>', 'Show covered changed lines in the output', false)
  .option('--shallowTests <bool>', 'Run test files only without deep in tests tree', true)
  .passThroughOptions()
  .enablePositionalOptions(); 


program
  .command('config')
  .description('Set or get configuration options')
  .option('--base <branch>', 'Set default base branch')
  .option('--shallowTests <bool>', 'Set default shallowTests value (true/false)')
  .action((opts) => {
    let config = readConfig();

    let updated = false;

    if (opts.base) {
      config.base = opts.base;
      updated = true;
      console.log(`Default base branch set to: ${opts.base}`);
    }

    if (typeof opts.shallowTests !== 'undefined') {
      config.shallowTests = opts.shallowTests === 'true' || opts.shallowTests === true;
      updated = true;
      console.log(`Default shallowTests set to: ${config.shallowTests}`);
    }
    if (updated) {
      writeConfig(config);
    } else {
      console.log('Current config:', config);
    }
    process.exit(0);
  })
  .enablePositionalOptions()


program.action((opts) => {
  const config = readConfig();
  const options = program.opts();
  console.log(`Current config: ${JSON.stringify(config, null, 2)}`);
  console.log(`Current options: ${JSON.stringify(options, null, 2)}`);
  console.log(`Current wqwqw: ${JSON.stringify(opts, null, 2)}`);
  
  // Use config base if not provided in CLI
  if (!options.base && config.base) {
    options.base = config.base;
  } else if (!options.base) {
    options.base = 'origin/main';
  }
  // Use config shallowTests if not provided in CLI
  console.log(`Using shallowTests: ${options.shallowTests} ${config.shallowTests}`);

  options.shallowTests = config.shallowTests ?? options.shallowTests;

  console.log(`Final options: ${JSON.stringify(options, null, 2)}`);

  main(options);
});

await program.parseAsync(process.argv);