#!/usr/bin/env node

import { Command } from 'commander';
import { main } from './src/cli.js';

const program = new Command();
program
  .name('mo3ta-coverage')
  .description('Run tests and report uncovered changed lines in a PR. Checks cumulative coverage for all changed lines against a specified limit. Useful for CI and code review workflows.')
  .option('--base <branch>', 'Base branch to compare against (e.g., origin/main)', 'origin/main')
  .option('--lcov <path>', 'Path to lcov.info file generated by test coverage tools', 'coverage/lcov.info')
  .option('--limit <percent>', 'Minimum required coverage percentage for all changed lines (e.g., 80)', '80')
  .option('--showCovered', 'Show covered changed lines in the output', false);

program.parse(process.argv);
const options = program.opts();

main(options);